version: '3.5'
services:
  kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: unless-stopped
    ports:
      - "5601:5601"
    networks:
      - elastic
    volumes:
      - /Users/louis/Documents/volumes/kibana/data:/usr/share/kibana/data
      - /Users/louis/Documents/volumes/kibana/config:/usr/share/kibana/config
      - /Users/louis/Documents/volumes/kibana/plugins:/usr/share/kibana/plugins
networks:
  elastic:
    driver: bridge