version: '3.5'

services:
  mongo:
    image: arm64v8/mongo:5.0.20
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
      TZ: "Asia/Shanghai"
    volumes:
    - /Users/louis/Documents/volumes/mongo/data:/data/db
    - /Users/louis/Documents/volumes/mongo/conf:/data/conf
    - /Users/louis/Documents/volumes/mongo/logs:/data/log
    ports:
    - "27017:27017"
    # restart: always
    command: --config /data/conf/mongod.conf