version: '3.5'

services:
  emqx:
    # restart: always
    image: emqx/emqx:latest
    container_name: emqx
    volumes:
      - ./data:/opt/emqx/data
      - ./log:/opt/emqx/log
      - ./etc:/opt/emqx/etc
    ports:
      - "18083:18083"
      - "1883:1883"
      - "8883:8883"
      - "8081:8081"
    environment:
      EMQX_NAME: emqx
