version: "3.7"
services:
  master:
    image: mysql:8.0
    container_name: mysql
    restart: always
    privileged: true
    ports:
      - "3306:3306"
    volumes:
      - /data/docker/mysql/log:/var/log/mysql
      #数据挂载
      - /data/docker/mysql/data:/var/lib/mysql
      #配置挂载
      - /data/docker/mysql/conf.d:/etc/mysql/conf.d
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=123456